import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import cm


def generate_digest_pdf(digest, user) -> str:
    os.makedirs("./digests", exist_ok=True)
    filename = f"./digests/digest_{user.id}_{digest.id}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    INDIGO = colors.HexColor('#6366F1')
    DARK = colors.HexColor('#0F172A')
    LIGHT_BG = colors.HexColor('#F1F5F9')
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=22, textColor=INDIGO, spaceAfter=6)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'], fontSize=11, textColor=colors.grey, spaceAfter=20)
    heading_style = ParagraphStyle('Heading', parent=styles['Heading2'], fontSize=14, textColor=DARK, spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=16, spaceAfter=6)
    story = []
    story.append(Paragraph("AlphaMind Weekly Investment Digest", title_style))
    story.append(Paragraph(f"For {user.username} | {datetime.now().strftime('%d %B %Y')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=INDIGO))
    story.append(Spacer(1, 0.5*cm))
    if digest.market_summary:
        story.append(Paragraph("Market Summary", heading_style))
        m = digest.market_summary
        nifty_p = m.get('nifty_price', 0)
        bank_p = m.get('banknifty_price', 0)
        data = [
            ['Index', 'Price', 'Weekly Change'],
            ['NIFTY 50', f"Rs {nifty_p:,.0f}" if nifty_p else 'N/A', f"{m.get('nifty_change_pct', 0):+.2f}%"],
            ['BANKNIFTY', f"Rs {bank_p:,.0f}" if bank_p else 'N/A', f"{m.get('banknifty_change_pct', 0):+.2f}%"],
        ]
        t = Table(data, colWidths=[5*cm, 5*cm, 5*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), INDIGO),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.lightgrey),
            ('BACKGROUND', (0,1), (-1,-1), LIGHT_BG),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
        ]))
        story.append(t)
        story.append(Paragraph(f"<b>Market Sentiment:</b> {m.get('sentiment', 'Neutral')}", body_style))
        story.append(Spacer(1, 0.3*cm))
    if digest.ai_suggestions:
        story.append(Paragraph("AI Investment Suggestions", heading_style))
        ai = digest.ai_suggestions
        if ai.get('executive_summary'):
            story.append(Paragraph(ai['executive_summary'], body_style))
        for s in ai.get('suggestions', []):
            story.append(Paragraph(f"- {s}", body_style))
        story.append(Spacer(1, 0.3*cm))
    if digest.portfolio_summary:
        story.append(Paragraph("Portfolio Intelligence", heading_style))
        p = digest.portfolio_summary
        story.append(Paragraph(f"<b>Avg Score:</b> {p.get('avg_score', 'N/A')}/100", body_style))
        story.append(Paragraph(f"<b>Health Score:</b> {p.get('health_score', 'N/A')}/100", body_style))
        if p.get('buy_recommendations'):
            story.append(Paragraph(f"<b>Top Buy Picks:</b> {', '.join(p['buy_recommendations'])}", body_style))
    if digest.watchlist_insights:
        story.append(Paragraph("Watchlist Insights", heading_style))
        w = digest.watchlist_insights
        symbols = w.get('watchlist_symbols', [])
        story.append(Paragraph(f"Watching: {', '.join(symbols) if symbols else 'No stocks in watchlist'}", body_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(
        "This report is generated by AlphaMind AI for informational purposes only. Not financial advice.",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
    ))
    doc.build(story)
    return filename
