""" add insight to institutional_holdings

Revision ID: 238341f257a9
Revises: 65e0e6d3c96d
Create Date: 2026-06-24 17:27:28.283222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '238341f257a9'
down_revision: Union[str, Sequence[str], None] = '65e0e6d3c96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_holdings', sa.Column('insight', sa.String(), nullable=False))
    op.add_column('institutional_holdings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('institutional_holdings', 'promoter_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('institutional_holdings', 'fii_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('institutional_holdings', 'dii_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('institutional_holdings', 'public_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_institutional_holdings_symbol'), table_name='institutional_holdings')
    op.create_index(op.f('ix_institutional_holdings_symbol'), 'institutional_holdings', ['symbol'], unique=False)
    op.drop_column('institutional_holdings', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_holdings', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_institutional_holdings_symbol'), table_name='institutional_holdings')
    op.create_index(op.f('ix_institutional_holdings_symbol'), 'institutional_holdings', ['symbol'], unique=True)
    op.alter_column('institutional_holdings', 'public_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('institutional_holdings', 'dii_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('institutional_holdings', 'fii_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('institutional_holdings', 'promoter_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('institutional_holdings', 'created_at')
    op.drop_column('institutional_holdings', 'insight')
    # ### end Alembic commands ###
