""" Add news_cache table

Revision ID: c7672605627d
Revises: c81fc8c00f21
Create Date: 2026-06-24 15:19:27.748196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7672605627d'
down_revision: Union[str, Sequence[str], None] = 'c81fc8c00f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_cache_id'), 'news_cache', ['id'], unique=False)
    op.create_index(op.f('ix_news_cache_symbol'), 'news_cache', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_cache_symbol'), table_name='news_cache')
    op.drop_index(op.f('ix_news_cache_id'), table_name='news_cache')
    op.drop_table('news_cache')
    # ### end Alembic commands ###
