""" Add institutional_holdings table

Revision ID: c81fc8c00f21
Revises: d352e7f9f2d4
Create Date: 2026-06-24 15:16:44.038559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81fc8c00f21'
down_revision: Union[str, Sequence[str], None] = 'd352e7f9f2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('promoter_pct', sa.Float(), nullable=True),
    sa.Column('fii_pct', sa.Float(), nullable=True),
    sa.Column('dii_pct', sa.Float(), nullable=True),
    sa.Column('public_pct', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_holdings_id'), 'institutional_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_institutional_holdings_symbol'), 'institutional_holdings', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutional_holdings_symbol'), table_name='institutional_holdings')
    op.drop_index(op.f('ix_institutional_holdings_id'), table_name='institutional_holdings')
    op.drop_table('institutional_holdings')
    # ### end Alembic commands ###
